# syntax=docker/dockerfile:1
FROM python:3.11-trixie AS build

WORKDIR src/

COPY ./ ./
RUN pip install --no-cache-dir poetry==2.2.1
RUN poetry build --format wheel

FROM python:3.11-trixie

RUN pip install --no-cache-dir apache-beam[gcp]==2.69.0

COPY --from=build /src/dist/*.whl .
COPY --from=apache/beam_python3.11_sdk:2.69.0 /opt/apache/beam /opt/apache/beam

RUN pip install --no-cache *.whl

# Set the entrypoint to Apache Beam SDK launcher.
ENTRYPOINT ["/opt/apache/beam/boot"]
