/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/9.2.0/userguide/building_java_projects.html in the Gradle documentation.
 */

plugins {
    // Apply the application plugin to add support for building a CLI application in Java.
    application
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    // Use JUnit Jupiter for testing.
    testImplementation(libs.junit.jupiter)

    testRuntimeOnly("org.junit.platform:junit-platform-launcher")

    // This dependency is used by the application.
    implementation(libs.guava)
    implementation(platform(libs.beam.sdks.java.google.cloud.platform.bom))
    implementation(libs.jackson.annotations)
    implementation(libs.jackson.databind)
    implementation(libs.log4j.slf4j.impl)
    implementation(libs.mongodb.driver.sync)
    compileOnly(libs.auto.value.annotations)
    annotationProcessor(libs.auto.value)
    implementation("org.apache.beam:beam-sdks-java-core")
    implementation("org.apache.beam:beam-runners-direct-java")
    implementation("org.apache.beam:beam-runners-google-cloud-dataflow-java")
    implementation("org.apache.beam:beam-sdks-java-io-elasticsearch")
    implementation("org.apache.beam:beam-sdks-java-io-mongodb")
    implementation("org.apache.beam:beam-sdks-java-io-rrio")
}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

application {
    // Define the main class for the application.
    mainClass = "app.App"
}

tasks.named<Test>("test") {
    doFirst {
        val envs: Map<String, String> = mapOf(
            "ES_HOSTS" to "192.168.1.1:9200,192.168.1.2:9200",
            "ES_INDEX" to "my_index",
            "ES_TYPE" to "_doc",
            "ES_USERNAME" to "my_username",
            "ES_PASSWORD" to "my_password",
            "ES_TRUST_SELF_SIGNED_CERTS" to "true",
            "ES_KEY_STORE_PATH" to "abc",
            "ES_KEY_STORE_PASSWORD" to "abc",
            "MONGO_HOST" to "192.168.1.1",
            "MONGO_DB" to "my_db",
            "MONGO_COLLECTION" to "my_collection",
            "MONGO_USERNAME" to "my_username",
            "MONGO_PASSWORD" to "my_password",
            "SOME_KEY" to "some_key"
        )

        environment(envs)
    }
    // Use JUnit Platform for unit tests.
    useJUnitPlatform()
}
