name: Java CI

on: [push]

jobs:
  unittest:
    if: github.ref != 'refs/head/main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Run unit test
        run: cd java ; make utest
